services:
  samba:
    image: dperson/samba
    container_name: npaper-nas
    restart: always
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /srv/npaper/biblioteca:/mnt/biblioteca
      - /srv/npaper/www:/mnt/www
    command: >
      -u "bibliotecario;senha123"
      -u "estudante;aluno123"
      -s "Acervo;/mnt/biblioteca;yes;no;no;bibliotecario;estudante"
      -s "Website;/mnt/www;yes;no;no;bibliotecario"
    networks:
      - npaper-network

  db:
    image: mariadb:10.11
    container_name: npaper-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: npaper_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" # <--- ADICIONE ESTA LINHA
    networks:
      - npaper-network

  php:
    build: 
      context: .
      dockerfile: php.Dockerfile
    container_name: npaper-php
    restart: always
    volumes:
      - /srv/npaper/www:/var/www/html
      - /srv/npaper/biblioteca:/var/www/biblioteca
      - /srv/npaper/www/thumbs:/var/www/html/thumbs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npaper-network

  web:
    image: nginx:latest
    container_name: npaper-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - /srv/npaper/www:/var/www/html
      - /srv/npaper/biblioteca:/var/www/html/acervo
      - /srv/npaper/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - npaper-network
    depends_on:
      - php
      - db

networks:
  npaper-network:
    driver: bridge

volumes:
  db_data: